---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-spinoperator-dev-v1alpha1-spinapp
  failurePolicy: Fail
  name: mspinapp.kb.io
  rules:
  - apiGroups:
    - core.spinkube.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spinapps
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-spinoperator-dev-v1alpha1-spinappexecutor
  failurePolicy: Fail
  name: mspinappexecutor.kb.io
  rules:
  - apiGroups:
    - core.spinkube.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spinappexecutors
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-spinoperator-dev-v1alpha1-spinapp
  failurePolicy: Fail
  name: vspinapp.kb.io
  rules:
  - apiGroups:
    - core.spinkube.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spinapps
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-spinoperator-dev-v1alpha1-spinappexecutor
  failurePolicy: Fail
  name: vspinappexecutor.kb.io
  rules:
  - apiGroups:
    - core.spinkube.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spinappexecutors
  sideEffects: None
