# permissions for end users to edit spinapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: spinapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: spin-operator
    app.kubernetes.io/part-of: spin-operator
    app.kubernetes.io/managed-by: kustomize
  name: spinapp-editor-role
rules:
- apiGroups:
  - core.spinoperator.dev
  resources:
  - spinapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.spinoperator.dev
  resources:
  - spinapps/status
  verbs:
  - get
