apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "spin-operator.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "spin-operator.fullname" . }}-serving-cert
  labels:
  {{- include "spin-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "spin-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-core-spinoperator-dev-v1-spinapp
  failurePolicy: Fail
  name: mspinapp.kb.io
  rules:
  - apiGroups:
    - core.spinoperator.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spinapps
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "spin-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-core-spinoperator-dev-v1-spinappexecutor
  failurePolicy: Fail
  name: mspinappexecutor.kb.io
  rules:
  - apiGroups:
    - core.spinoperator.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spinappexecutors
  sideEffects: None