apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "spin-operator.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "spin-operator.fullname" . }}-serving-cert
  labels:
  {{- include "spin-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "spin-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-core-spinoperator-dev-v1alpha1-spinapp
  failurePolicy: Fail
  name: vspinapp.kb.io
  rules:
  - apiGroups:
    - core.spinkube.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spinapps
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "spin-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-core-spinoperator-dev-v1alpha1-spinappexecutor
  failurePolicy: Fail
  name: vspinappexecutor.kb.io
  rules:
  - apiGroups:
    - core.spinkube.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spinappexecutors
  sideEffects: None