apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: spintainer-spinapp
spec:
  image: "ghcr.io/spinkube/spin-operator/hello-world:20240708-130250-gfefd2b1"
  replicas: 1
  executor: spintainer
