---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: spinappexecutors.core.spinoperator.dev
spec:
  group: core.spinoperator.dev
  names:
    kind: SpinAppExecutor
    listKind: SpinAppExecutorList
    plural: spinappexecutors
    singular: spinappexecutor
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: SpinAppExecutor is the Schema for the spinappexecutors API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: SpinAppExecutorSpec defines the desired state of SpinAppExecutor
            properties:
              createDeployment:
                description: |-
                  CreateDeployment specifies whether the Executor wants the SpinKube operator
                  to create a deployment for the application or if it will be realized externally.
                type: boolean
              deploymentConfig:
                description: |-
                  DeploymentConfig specifies how the deployment should be configured when
                  createDeployment is true.
                properties:
                  runtimeClassName:
                    description: |-
                      RuntimeClassName is the runtime class name that should be used by pods created
                      as part of a deployment.
                    type: string
                required:
                - runtimeClassName
                type: object
            required:
            - createDeployment
            type: object
          status:
            description: SpinAppExecutorStatus defines the observed state of SpinAppExecutor
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
